/**
 * 对于所有的枚举常量进行映射。
 * @type 枚举常量
 */
var ENUM_CONSTANT= {
    "SECURITIES_ACCOUNT_NUMBER": "SECURITIES_ACCOUNT_NUMBER",
    "TRADER_NAME": "TRADER_NAME",
    "SHORT_LEGAL_NAME_OF_FIRM": "SHORT_LEGAL_NAME_OF_FIRM",
    "CONTACT_METHOD_OF_TRADER": "CONTACT_METHOD_OF_TRADER",
    "MEMBERS_OR_CLIENTS": "MEMBERS_OR_CLIENTS",
    "NON_MARKET_MAKER": "NON_MARKET_MAKER",
    "MARGIN_SETTLEMENT_ACCOUNT_NUMBER": "MARGIN_SETTLEMENT_ACCOUNT_NUMBER",
    "MARGIN_CUSTODIAN_ACCOUNT_NUMBER": "MARGIN_CUSTODIAN_ACCOUNT_NUMBER",
    "MARGIN_SETTLEMENT_BANK_NAME": "MARGIN_SETTLEMENT_BANK_NAME",
    "MARGIN_CUSTODIAN_INSTITUTION_NAME": "MARGIN_CUSTODIAN_INSTITUTION_NAME",
    "REGISTRATION_NUMBER": "REGISTRATION_NUMBER",
    "SETTLEMENT_BANK_NAME": "SETTLEMENT_BANK_NAME",
    "CUSTODIAN_INSTITUTION_NAME": "CUSTODIAN_INSTITUTION_NAME",
    "SETTLEMENT_BANK_SORT_CODE": "SETTLEMENT_BANK_SORT_CODE",
    "CUSTODIAN_BANK_NAME": "CUSTODIAN_BANK_NAME",
    "CUSTODIAN_ACCOUNT_NAME": "CUSTODIAN_ACCOUNT_NAME",
    "CUSTODIAN_ACCOUNT_NUMBER": "CUSTODIAN_ACCOUNT_NUMBER",
    "MARGIN_SETTLEMENT_ACCOUNT_NAME": "MARGIN_SETTLEMENT_ACCOUNT_NAME",
    "MARGIN_CUSTODIAN_ACCOUNT_NAME": "MARGIN_CUSTODIAN_ACCOUNT_NAME",
    "CHINESE_NAME_OF_CASH_ACCOUNT": "CHINESE_NAME_OF_CASH_ACCOUNT",
    "STATUS_OF_SECURITIES_ACCOUNT": "STATUS_OF_SECURITIES_ACCOUNT",
    "REGISTERED_ADDRESS": "REGISTERED_ADDRESS",
    "STATUS_OF_CASH_ACCOUNT": "STATUS_OF_CASH_ACCOUNT",
    "MARGIN_SETTLEMENT_BANK_SORT_CODE": "MARGIN_SETTLEMENT_BANK_SORT_CODE",
    "MARGIN_CUSTODIAN_ENTITY_CODE": "MARGIN_CUSTODIAN_ENTITY_CODE",
    "CUSTODIAN_ENTITY_CODE": "CUSTODIAN_ENTITY_CODE",
    "FULL_LEGAL_CHINESE_NAME_OF_FIRM": "FULL_LEGAL_CHINESE_NAME_OF_FIRM",
    "SHORT_LEGAL_CHINESE_NAME_OF_FIRM": "SHORT_LEGAL_CHINESE_NAME_OF_FIRM",
    "TRADER_CHINESE_NAME": "TRADER_CHINESE_NAME",
    "ZIP_CODE": "ZIP_CODE",
    "CFETS_MARGIN_SETTLEMENT_ACCOUNT_NUMBER": "CFETS_MARGIN_SETTLEMENT_ACCOUNT_NUMBER",
    "OTHER_MARGIN_SETTLEMENT_ACCOUNT_NUMBER": "OTHER_MARGIN_SETTLEMENT_ACCOUNT_NUMBER",
    "FIRM_CODE": "FIRM_CODE",
    "MULTI_CURRENCY_ACCOUNT_DESCRIPTION": "MULTI_CURRENCY_ACCOUNT_DESCRIPTION",
    "COLLATERAL_MANAGEMENT_INSTITUTION_ID": "COLLATERAL_MANAGEMENT_INSTITUTION_ID",
    "COLLATERAL_MANAGEMENT_INSTITUTION_NAME": "COLLATERAL_MANAGEMENT_INSTITUTION_NAME",
    "INSTITUTION_GROUP_NAME": "INSTITUTION_GROUP_NAME",
    "FIRM_ID": "FIRM_ID",
    "CLEARING_INSTITUTION": "CLEARING_INSTITUTION",
    "SETTLEMENT_CURRENCY_NAME": "SETTLEMENT_CURRENCY_NAME",
    "SETTLEMENT_CURRENCY_REMARK": "SETTLEMENT_CURRENCY_REMARK",
    "CONTRA_CCY_SETTLEMENT_BANK_NAME": "CONTRA_CCY_SETTLEMENT_BANK_NAME",
    "CONTRA_CCY_CHINESE_NAME_OF_CASH_ACCOUNT": "CONTRA_CCY_CHINESE_NAME_OF_CASH_ACCOUNT",
    "CONTRA_CCY_ENGLISH_NAME_OF_CASH_ACCOUNT": "CONTRA_CCY_ENGLISH_NAME_OF_CASH_ACCOUNT",
    "CONTRA_CCY_SWIFT_CODE": "CONTRA_CCY_SWIFT_CODE",
    "CONTRA_CCY_NAME": "CONTRA_CCY_NAME",
    "CONTRA_CCY_REMARK": "CONTRA_CCY_REMARK",
    "INTERNAL_GROUP_THE_TRADER_BELONGED_TO": "INTERNAL_GROUP_THE_TRADER_BELONGED_TO",
    "DEAL_CONFIRM_CONTACT_NAME": "DEAL_CONFIRM_CONTACT_NAME",
    "DEPOSIT_ACCOUNT": "DEPOSIT_ACCOUNT",
    "CURRENT_ACCOUNT": "CURRENT_ACCOUNT",
    "CASH_ACCOUNT_NUMBER": "CASH_ACCOUNT_NUMBER",
    "HIGH_VALUE_PAYMENT_SYSTEM_CODE": "HIGH_VALUE_PAYMENT_SYSTEM_CODE",
    "SECURITIES_ACCOUNT_CHINESE_NAME": "SECURITIES_ACCOUNT_CHINESE_NAME",
    "RMB_MEMBER_ID": "RMB_MEMBER_ID",
    "FX_MEMBER_ID": "FX_MEMBER_ID",
    "FX_SYSTEM_ENGLISH_SHORT_NAME": "FX_SYSTEM_ENGLISH_SHORT_NAME",
    "OTHER_SYSTEM_CODE": "OTHER_SYSTEM_CODE",
    "CUSTODY_MANAGEMENT_INSTITUTION": "CUSTODY_MANAGEMENT_INSTITUTION",
    "INSTITUTION_ID_IN_COMSTAR_SYSTEM": "INSTITUTION_ID_IN_COMSTAR_SYSTEM",
    "SWIFT_BIC_CODE": "SWIFT_BIC_CODE",
    "USER_NAME": "USER_NAME",
    "PASSWORD": "PASSWORD",
    "MEMBER_TYPE": "MEMBER_TYPE",
    "PAYMENT_SYSTEM_CODE_OF_THE_LOCAL_PEOPLE_BANK": "PAYMENT_SYSTEM_CODE_OF_THE_LOCAL_PEOPLE_BANK",
    "SETTLEMENT_BANK_BIC_CODE": "SETTLEMENT_BANK_BIC_CODE",
    "ACCOUNTTYPE": "ACCOUNTTYPE",
    "BRANCHID": "BRANCHID",
    "SETTLEMENT_BANK_CHINESE_NAME": "SETTLEMENT_BANK_CHINESE_NAME",
    "USER_INPUT_TRADES": "USER_INPUT_TRADES",
    "AGENT_USER_INPUT_TRADES": "AGENT_USER_INPUT_TRADES",
    "CONTRA_CCY_SETTLEMENT_BANK_CHINESE_NAME": "CONTRA_CCY_SETTLEMENT_BANK_CHINESE_NAME",
    "CONTRA_CCY_CASH_ACCOUNT_NUMBER": "CONTRA_CCY_CASH_ACCOUNT_NUMBER",
    "CONTRA_CCY_HIGH_VALUE_PAYMENT_SYSTEM_CODE": "CONTRA_CCY_HIGH_VALUE_PAYMENT_SYSTEM_CODE",
    "SETTLEMENT_CURRENCY_NAME_OF_NEAR_LEG": "SETTLEMENT_CURRENCY_NAME_OF_NEAR_LEG",
    "CASH_ACCOUNT_NAME_OF_NEAR_LEG": "CASH_ACCOUNT_NAME_OF_NEAR_LEG",
    "CHINESE_NAME_OF_CASH_ACCOUNT_OF_NEAR_LEG": "CHINESE_NAME_OF_CASH_ACCOUNT_OF_NEAR_LEG",
    "SETTLEMENT_BANK_NAME_OF_NEAR_LEG": "SETTLEMENT_BANK_NAME_OF_NEAR_LEG",
    "SETTLEMENT_BANK_CHINESE_NAME_OF_NEAR_LEG": "SETTLEMENT_BANK_CHINESE_NAME_OF_NEAR_LEG",
    "CASH_ACCOUNT_NUMBER_OF_NEAR_LEG": "CASH_ACCOUNT_NUMBER_OF_NEAR_LEG",
    "HIGH_VALUE_PAYMENT_SYSTEM_CODE_OF_NEAR_LEG": "HIGH_VALUE_PAYMENT_SYSTEM_CODE_OF_NEAR_LEG",
    "SWIFT_BIC_CODE_OF_NEAR_LEG": "SWIFT_BIC_CODE_OF_NEAR_LEG",
    "CONTRA_CCY_NAME_OF_NEAR_LEG": "CONTRA_CCY_NAME_OF_NEAR_LEG",
    "CONTRA_CCY_ENGLISH_NAME_OF_CASH_ACCOUNT_OF_NEAR_LEG": "CONTRA_CCY_ENGLISH_NAME_OF_CASH_ACCOUNT_OF_NEAR_LEG",
    "CONTRA_CCY_CHINESE_NAME_OF_CASH_ACCOUNT_OF_NEAR_LEG": "CONTRA_CCY_CHINESE_NAME_OF_CASH_ACCOUNT_OF_NEAR_LEG",
    "CONTRA_CCY_SETTLEMENT_BANK_NAME_OF_NEAR_LEG": "CONTRA_CCY_SETTLEMENT_BANK_NAME_OF_NEAR_LEG",
    "CONTRA_CCY_SETTLEMENT_BANK_CHINESE_NAME_OF_NEAR_LEG": "CONTRA_CCY_SETTLEMENT_BANK_CHINESE_NAME_OF_NEAR_LEG",
    "CONTRA_CCY_CASH_ACCOUNT_NUMBER_OF_NEAR_LEG": "CONTRA_CCY_CASH_ACCOUNT_NUMBER_OF_NEAR_LEG",
    "CONTRA_CCY_HIGH_VALUE_PAYMENT_SYSTEM_CODE_OF_NEAR_LEG": "CONTRA_CCY_HIGH_VALUE_PAYMENT_SYSTEM_CODE_OF_NEAR_LEG",
    "CONTRA_CCY_SWIFT_CODE_OF_NEAR_LEG": "CONTRA_CCY_SWIFT_CODE_OF_NEAR_LEG",
    "SETTLEMENT_CURRENCY_NAME_OF_FAR_LEG": "SETTLEMENT_CURRENCY_NAME_OF_FAR_LEG",
    "CASH_ACCOUNT_NAME_OF_FAR_LEG": "CASH_ACCOUNT_NAME_OF_FAR_LEG",
    "CHINESE_NAME_OF_CASH_ACCOUNT_OF_FAR_LEG": "CHINESE_NAME_OF_CASH_ACCOUNT_OF_FAR_LEG",
    "SETTLEMENT_BANK_NAME_OF_FAR_LEG": "SETTLEMENT_BANK_NAME_OF_FAR_LEG",
    "SETTLEMENT_BANK_CHINESE_NAME_OF_FAR_LEG": "SETTLEMENT_BANK_CHINESE_NAME_OF_FAR_LEG",
    "CASH_ACCOUNT_NUMBER_OF_FAR_LEG": "CASH_ACCOUNT_NUMBER_OF_FAR_LEG",
    "HIGH_VALUE_PAYMENT_SYSTEM_CODE_OF_FAR_LEG": "HIGH_VALUE_PAYMENT_SYSTEM_CODE_OF_FAR_LEG",
    "SWIFT_BIC_CODE_OF_FAR_LEG": "SWIFT_BIC_CODE_OF_FAR_LEG",
    "CONTRA_CCY_NAME_OF_FAR_LEG": "CONTRA_CCY_NAME_OF_FAR_LEG",
    "TRADER_CODE": "TRADER_CODE",
    "CONTRA_CCY_ENGLISH_NAME_OF_CASH_ACCOUNT_OF_FAR_LEG": "CONTRA_CCY_ENGLISH_NAME_OF_CASH_ACCOUNT_OF_FAR_LEG",
    "CONTRA_CCY_CHINESE_NAME_OF_CASH_ACCOUNT_OF_FAR_LEG": "CONTRA_CCY_CHINESE_NAME_OF_CASH_ACCOUNT_OF_FAR_LEG",
    "CONTRA_CCY_SETTLEMENT_BANK_NAME_OF_FAR_LEG": "CONTRA_CCY_SETTLEMENT_BANK_NAME_OF_FAR_LEG",
    "CONTRA_CCY_SETTLEMENT_BANK_CHINESE_NAME_OF_FAR_LEG": "CONTRA_CCY_SETTLEMENT_BANK_CHINESE_NAME_OF_FAR_LEG",
    "CONTRA_CCY_CASH_ACCOUNT_NUMBER_OF_FAR_LEG": "CONTRA_CCY_CASH_ACCOUNT_NUMBER_OF_FAR_LEG",
    "CONTRA_CCY_HIGH_VALUE_PAYMENT_SYSTEM_CODE_OF_FAR_LEG": "CONTRA_CCY_HIGH_VALUE_PAYMENT_SYSTEM_CODE_OF_FAR_LEG",
    "CONTRA_CCY_SWIFT_CODE_OF_FAR_LEG": "CONTRA_CCY_SWIFT_CODE_OF_FAR_LEG",
    "CORRESPONDENT_BANK_ACCOUNT": "CORRESPONDENT_BANK_ACCOUNT",
    "CONTRA_CCY_CORRESPONDENT_BANK_ACCOUNT": "CONTRA_CCY_CORRESPONDENT_BANK_ACCOUNT",
    "INTERMEDIARY_BANK": "INTERMEDIARY_BANK",
    "CONTRA_CCY_INTERMEDIARY_BANK": "CONTRA_CCY_INTERMEDIARY_BANK",
    "INTERMEDIARY_BANK_BIC_CODE": "INTERMEDIARY_BANK_BIC_CODE",
    "CONTRA_CCY_INTERMEDIARY_BANK_BIC_CODE": "CONTRA_CCY_INTERMEDIARY_BANK_BIC_CODE",
    "INTERMEDIARY_BANK_ACCOUNT": "INTERMEDIARY_BANK_ACCOUNT",
    "CONTRA_CCY_INTERMEDIARY_BANK_ACCOUNT": "CONTRA_CCY_INTERMEDIARY_BANK_ACCOUNT",
    "INTERMEDIARY_BANK_OF_NEAR_LEG": "INTERMEDIARY_BANK_OF_NEAR_LEG",
    "CONTRA_CCY_INTERMEDIARY_BANK_OF_FAR_LEG": "CONTRA_CCY_INTERMEDIARY_BANK_OF_FAR_LEG",
    "INTERMEDIARY_BANK_BIC_CODE_OF_NEAR_LEG": "INTERMEDIARY_BANK_BIC_CODE_OF_NEAR_LEG",
    "CONTRA_CCY_INTERMEDIARY_BANK_BIC_CODE_OF_FAR_LEG": "CONTRA_CCY_INTERMEDIARY_BANK_BIC_CODE_OF_FAR_LEG",
    "INTERMEDIARY_BANK_ACCOUNT_OF_NEAR_LEG": "INTERMEDIARY_BANK_ACCOUNT_OF_NEAR_LEG",
    "SECURITIES_ACCOUNT_NAME": "SECURITIES_ACCOUNT_NAME",
    "CONTRA_CCY_INTERMEDIARY_BANK_ACCOUNT_OF_FAR_LEG": "CONTRA_CCY_INTERMEDIARY_BANK_ACCOUNT_OF_FAR_LEG",
    "CORRESPONDENT_BANK_ACCOUNT_OF_NEAR_LEG": "CORRESPONDENT_BANK_ACCOUNT_OF_NEAR_LEG",
    "CONTRA_CCY_CORRESPONDENT_BANK_ACCOUNT_OF_FAR_LEG": "CONTRA_CCY_CORRESPONDENT_BANK_ACCOUNT_OF_FAR_LEG",
    "PERSON_ID": "PERSON_ID",
    "CASH_ACCOUNT_NAME": "CASH_ACCOUNT_NAME",
    "UNIFIED_SOCIAL_CREDIT_CODE": "UNIFIED_SOCIAL_CREDIT_CODE",
    "ALTERNATIVE_NAME": "ALTERNATIVE_NAME",
    "DEPARTMENT": "DEPARTMENT",
    "MARKET_MAKER": "MARKET_MAKER",
    "ELIGIBLE_COUNTERPARTY": "ELIGIBLE_COUNTERPARTY",
    "EXECUTION_VENUE": "EXECUTION_VENUE",
    "FAX_NO": "FAX_NO",
    "LEGAL_REPRESENTATIVE": "LEGAL_REPRESENTATIVE",
    "FULL_LEGAL_NAME_OF_FIRM": "FULL_LEGAL_NAME_OF_FIRM",
    "POSTAL_ADDRESS": "POSTAL_ADDRESS",
    "PHONE_NUMBER": "PHONE_NUMBER",
    "CONTACT_NAME": "CONTACT_NAME"
};


/**
 * 对于枚举常量的映射
 * @param original 原始值
 * @returns {*} 对应的数据库真实值
 */
function map(original) {
    var result = ENUM_CONSTANT[original];
    if (!!result
        && result != "") {
        return result;
    }
    return original;
}

/**
 * 自定义映射
 * @param original 原始值
 * @param constantMap 映射列表.是一个JSON对象。
 * @see ENUM_CONSTANT
 */
function defineMap(original, constantMap) {
    var result = constantMap[original];
    if (!!result
        && result != "") {
        return result;
    }
    return original;
}

/**
 * 获取格式化的日期。如果不需要对利率进行互换，使用这个。
 * @param original 原始日期。如：20170216-14:53:35.026
 * @returns {*} 将-替换后的日期。如：20170216 14:53:35.026
 */
function getFormatDate(original) {
    var dateReg = /^[0-9]{8}-[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}$/;
    if (dateReg.test(original)) {
        return original.replace('-', ' ');
    }
    return original;
}

/**
 * 对日期进行格式化；对利率进行处理。
 * @param nodeName 节点名称
 * @param original 原始值
 */
function getFormatDateAndRate(nodeName, original) {
    if("Price" == nodeName) {
        return getRate(original);
    } else {
        return getFormatDate(original);
    }
}

/**
 * 获取当前金额对应的利率
 * @param original 原始金额
 * @returns {number} 对金额进行运算之后的结果
 */
function getRate(original) {
    return original / 100.0;
}




